#!/usr/bin/env bash
# Tell the story of passwd script

# قراءة كل سطر من الملف /etc/passwd
while IFS=: read -r username _ userid groupid _ home_dir shell; do
    # عرض المعلومات بصيغة القصة
    echo "The user $username is part of the $groupid gang, lives in $home_dir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
