#!/usr/bin/env bash
# Display hours from 0 to 12 and minutes from 1 to 59 for each hour

i=0
while [ $i -le 12 ]; do
    echo "Hour: $i"

    s=1
    while [ $s -le 59 ]; do
        echo $s
        s=$((s + 1))  # Correctly increment minutes by 1
    done

    i=$((i + 1))  # Increment hour by 1
done
