#!/usr/bin/env bash

# قائمة جميع الملفات التي تحتوي على شرطة في اسم الملف
for file in *-*
do
    # استبعاد الملفات المخفية
    if [[ -f "$file" && "$file" != .* ]]; then
        # استخراج الجزء بعد الشرطة الأولى
        name_after_dash="${file#*-}"
        echo "$name_after_dash"
    fi
done
